# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sorohimm/CLionProjects/GayEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sorohimm/CLionProjects/GayEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sorohimm/CLionProjects/GayEngine/CMakeFiles /Users/sorohimm/CLionProjects/GayEngine/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sorohimm/CLionProjects/GayEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GayEngine

# Build rule for target.
GayEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GayEngine
.PHONY : GayEngine

# fast build rule for target.
GayEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/build
.PHONY : GayEngine/fast

sources/Draw.o: sources/Draw.cpp.o

.PHONY : sources/Draw.o

# target to build an object file
sources/Draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Draw.cpp.o
.PHONY : sources/Draw.cpp.o

sources/Draw.i: sources/Draw.cpp.i

.PHONY : sources/Draw.i

# target to preprocess a source file
sources/Draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Draw.cpp.i
.PHONY : sources/Draw.cpp.i

sources/Draw.s: sources/Draw.cpp.s

.PHONY : sources/Draw.s

# target to generate assembly for a file
sources/Draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Draw.cpp.s
.PHONY : sources/Draw.cpp.s

sources/Engine.o: sources/Engine.cpp.o

.PHONY : sources/Engine.o

# target to build an object file
sources/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Engine.cpp.o
.PHONY : sources/Engine.cpp.o

sources/Engine.i: sources/Engine.cpp.i

.PHONY : sources/Engine.i

# target to preprocess a source file
sources/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Engine.cpp.i
.PHONY : sources/Engine.cpp.i

sources/Engine.s: sources/Engine.cpp.s

.PHONY : sources/Engine.s

# target to generate assembly for a file
sources/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Engine.cpp.s
.PHONY : sources/Engine.cpp.s

sources/Input.o: sources/Input.cpp.o

.PHONY : sources/Input.o

# target to build an object file
sources/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Input.cpp.o
.PHONY : sources/Input.cpp.o

sources/Input.i: sources/Input.cpp.i

.PHONY : sources/Input.i

# target to preprocess a source file
sources/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Input.cpp.i
.PHONY : sources/Input.cpp.i

sources/Input.s: sources/Input.cpp.s

.PHONY : sources/Input.s

# target to generate assembly for a file
sources/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Input.cpp.s
.PHONY : sources/Input.cpp.s

sources/Level.o: sources/Level.cpp.o

.PHONY : sources/Level.o

# target to build an object file
sources/Level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Level.cpp.o
.PHONY : sources/Level.cpp.o

sources/Level.i: sources/Level.cpp.i

.PHONY : sources/Level.i

# target to preprocess a source file
sources/Level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Level.cpp.i
.PHONY : sources/Level.cpp.i

sources/Level.s: sources/Level.cpp.s

.PHONY : sources/Level.s

# target to generate assembly for a file
sources/Level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Level.cpp.s
.PHONY : sources/Level.cpp.s

sources/Player.o: sources/Player.cpp.o

.PHONY : sources/Player.o

# target to build an object file
sources/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Player.cpp.o
.PHONY : sources/Player.cpp.o

sources/Player.i: sources/Player.cpp.i

.PHONY : sources/Player.i

# target to preprocess a source file
sources/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Player.cpp.i
.PHONY : sources/Player.cpp.i

sources/Player.s: sources/Player.cpp.s

.PHONY : sources/Player.s

# target to generate assembly for a file
sources/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Player.cpp.s
.PHONY : sources/Player.cpp.s

sources/Update.o: sources/Update.cpp.o

.PHONY : sources/Update.o

# target to build an object file
sources/Update.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Update.cpp.o
.PHONY : sources/Update.cpp.o

sources/Update.i: sources/Update.cpp.i

.PHONY : sources/Update.i

# target to preprocess a source file
sources/Update.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Update.cpp.i
.PHONY : sources/Update.cpp.i

sources/Update.s: sources/Update.cpp.s

.PHONY : sources/Update.s

# target to generate assembly for a file
sources/Update.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/Update.cpp.s
.PHONY : sources/Update.cpp.s

sources/main.o: sources/main.cpp.o

.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i

.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s

.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GayEngine.dir/build.make CMakeFiles/GayEngine.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GayEngine"
	@echo "... sources/Draw.o"
	@echo "... sources/Draw.i"
	@echo "... sources/Draw.s"
	@echo "... sources/Engine.o"
	@echo "... sources/Engine.i"
	@echo "... sources/Engine.s"
	@echo "... sources/Input.o"
	@echo "... sources/Input.i"
	@echo "... sources/Input.s"
	@echo "... sources/Level.o"
	@echo "... sources/Level.i"
	@echo "... sources/Level.s"
	@echo "... sources/Player.o"
	@echo "... sources/Player.i"
	@echo "... sources/Player.s"
	@echo "... sources/Update.o"
	@echo "... sources/Update.i"
	@echo "... sources/Update.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

